### ISSUE TITLE
Support for fasthttp

### ISSUE THREAD

**Issue by flyhard** [elnormous/contenttype#1]
I would like to have support for fasthttp. I have made a try at fixing it, PR coming soon

**Comment by flyhard** [comment]
One could fix the compatibility issue maybe with overloading the method for each framework, but I was thinking that there might be many frameworks this is useful for, so extracting the library dependent stuff to special packages might be in order.

**Comment by elnormous** [comment]
What do you mean by "support for fasthttp"? What needs to be fixed? The library can be used anywhere by just importing it. Can you please explain what you are trying to do?

**Comment by flyhard** [comment]
the library github.com/valyala/fasthttp is  a failry common http server that is not using the standard library. They access the headers differently.

**Comment by elnormous** [comment]
This seems wrong and does not follow Go guidelines. Internals should not be exposed outside of the package. Can you provide examples of other projects doing this just to be compatible with fasthttp and the documentation which states that this is needed to be compatible (and how it is used)?

**Comment by flyhard** [comment]
OK. I'll rework it differently. Let me know what you think of that approach
